### PR TITLE
Update default module-depth to -1

### PR DESCRIPTION
**Pull request by rowleyaj**
This is now the default in terraform

### CODE REVIEW

**Comment by mlrobinson** [comment]
Looks good, though since it is the Terraform default now, do we even need to specify it?

**Comment by rowleyaj** [comment]
@mlrobinson I think we still need to specify it to allow it to be overridden. Oddly though this isn't even exposed in the rake tasks anyway.

**Comment by josephholsten** [comment]
the alternative might be

```
    def tf_plan(output_file = nil, state_file = nil, module_depth = nil)
      cmd = 'terraform plan'
      cmd << " -module-depth #{module_depth}" unless module_depth.nil?
      state_file && cmd << " -state #{state_file}"
      output_file && cmd << " -out #{output_file}"
      system(cmd)
    end
```

**Comment by josephholsten** [comment]
I don't actually want to use the above implementation though. Explicitly specifying `-module-depth` makes it play nicely with different releases of tf, and I'd rather know exactly how tf is going to respond than trust whatever the default was as the time.

**Pull request closed without merging**
